// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsdjNUFvK5NqIC-nBKno06g3lGlFd5n78',
    appId: '1:1045221426211:web:7def4bb0fdc6e277105d96',
    messagingSenderId: '1045221426211',
    projectId: 'yitadee-app',
    authDomain: 'yitadee-app.firebaseapp.com',
    storageBucket: 'yitadee-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3deIjVCmV-UhJeDUzsp7qSHAylk0KpB8',
    appId: '1:732965232392:android:1705ad63eef48fc39416bd',
    messagingSenderId: '732965232392',
    projectId: 'app-yitadee',
    storageBucket: 'app-yitadee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVaOLec6pk33goKF0ci4g9dhGlL9JPkP0',
    appId: '1:732965232392:ios:d3903408b1b7fe6a9416bd', 
    messagingSenderId: '732965232392',
    projectId: 'app-yitadee',
    storageBucket: 'app-yitadee.firebasestorage.app',
    iosBundleId: 'com.gotitmaderecords.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvjFs0nZJHhUCuvX4ld0pdjUC0fjnkCs',
    appId: '1:1045221426211:ios:58fef95c8c398f8e105d96',
    messagingSenderId: '1045221426211',
    projectId: 'yitadee-app',
    storageBucket: 'yitadee-app.firebasestorage.app',
    iosBundleId: 'com.example.yitadeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsdjNUFvK5NqIC-nBKno06g3lGlFd5n78',
    appId: '1:1045221426211:web:6926fc2c9e2be27a105d96',
    messagingSenderId: '1045221426211',
    projectId: 'yitadee-app',
    authDomain: 'yitadee-app.firebaseapp.com',
    storageBucket: 'yitadee-app.firebasestorage.app',
  );
}
